### ISSUE TITLE
Home-brew Installation

### ISSUE THREAD

**Issue by lucycamlin** [IdeasOnCanvas/ScreenshotFramer#22]
I tried installing Home-brew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
error: could not lock config file /usr/local/Homebrew/.git/config: Permission denied
fatal: could not set 'core.repositoryformatversion' to '0'
Failed during: git init -q

**Comment by Patrick-Kladek** [comment]
It seems like you have problems installing homebrew. I cannot help you with that kind of issue as I do not work for homebrew. Maybe stackoverflow would be a better place to ask for help
