### ISSUE TITLE
Option to show frame outline for easier alignment

### ISSUE THREAD

**Issue by jpstuehler** [IdeasOnCanvas/ScreenshotFramer#27]
Thanks for building this. In my project we are at 17 supported languages by now so it's about time to simplify the screenshot creation.

What I've been struggling with a bit while getting everything setup was aligning everything. For the content, device and text layers it would be of great help to be able to show an outline or e.g. 30% red background while positioning everything.

**Comment by schwmi** [comment]
I think this works already. You can press CMD+L to get a red border around your content :)

**Comment by jpstuehler** [comment]
That's almost what I wanted and actually perfectly sufficient. Thanks!

Feel free to close this if that's also a sufficient solution for you guys.
